name: MRTPA
main: me.wolf_131.mrtpa.Main
version: 2.0.0
author: Wolf_131
commands:
  tpa:
    aliases: [tp]
  tpaceitar:
    aliases: [tpaccept]
  tpnegar:
    aliases: [tpdeny]
  tptoggle:
  tpo:
    aliases: [tpoutro]
  tpaqui:
    aliases: [tphere]
  tpcancelar:
    aliases: [tpcancel]
  tpaleatorio:
    aliases: [randomtp]
